---
- hosts: local_mac
  tasks:
  - block:
    - name: homebrew update
      homebrew:
        update_homebrew: true
        upgrade_all: yes
    - name: language_env ex) android used java(openjava) different from spring boot java (adoptopenjava).
      homebrew:
        name: anyenv
        state: absent
    # this is not aws official, but this formular use aws github and more stable than aws official pip repo.
    # you update awscli after you install this formular.
    # https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb
    - name: aws dev
      homebrew:
        name: awscli
        state: present
    - name: brew tap is needed to install aws-sam-cli
      homebrew_tap:
        name: aws/tap
        state: present
    - name: aws-sam-cli install 
      homebrew:
        name: aws-sam-cli
        state: present
    - name: dep install. this is golang dependency tool
      homebrew:
        name: dep
        state: present
    - name: IDE install
      homebrew_cask:
        name: visual-studio-code
        state: present
  tags:
    - homebrew
